services:
  star-wars-api:
    container_name: star-wars-api
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: development
      DATABASE_URL: postgres://postgres:root@db:5432/data_swapi
    volumes:
      - .:/app
    command: npm run dev

  db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: data_swapi
      POSTGRES_PORT: 5432
    ports:
      - '5432:5432'
    volumes:
      - ./data-postgres:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d data_swapi']
      interval: 5s
      timeout: 5s
      retries: 5

  migration:
    container_name: migration
    build:
      context: .
      dockerfile: Dockerfile.migrate
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://postgres:root@db:5432/data_swapi
    command: npm run migrate
