services:
  star-wars-api:
    image: star-wars-api:latest
    container_name: star-wars-api
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: production
      DATABASE_URL: postgres://postgres:root@db:5432/sw_api
    volumes:
      - .:/app

  db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: sw_api
      POSTGRES_PORT: 5432
    ports:
      - '5432:5432'
    volumes:
      - ./data-postgres:/var/lib/postgresql/data
