version: '3.8' 
services:
  star-wars-api:
    image: star-wars-api:latest
    container_name: star-wars-api
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      
    volumes:
      - .:/app
